import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'stretch',
      justifyContent: 'center',
    },
    logo:{
      fontSize:75,
      borderBottomWidth:1,
      borderBottomColor:'#000',
    },
    secondTitle:{
      fontSize:32,
    },
    btn:{
      borderWidth:1,
      borderColor:'#000',
      paddingHorizontal:20,
      paddingVertical:10,
      borderRadius:4,marginVertical:10,
    },
    success:{
      backgroundColor:'#198754',
    },
    warning:{
      backgroundColor:'#ffc107',
    },
    primary:{
      backgroundColor:'#0d6efd',
    },
    danger:{
      backgroundColor:'#dc3545',
    },
    info:{
      backgroundColor:'#0dcaf0',
    },
    dark:{
      backgroundColor:'#212529',
    },
    light:{
      backgroundColor:'#f8f9fa',
    },
    secondary:{
      backgroundColor:'#6c757d',
    },
    text_success:{
      color:'#FFFFFF',
    },
    text_warning:{
      color:'#000000',
    },
    text_primary:{
      color:'#FFFFFF',
    },
    text_danger:{
      color:'#FFFFFF',
    },
    text_info:{
      color:'#000000',
    },
    text_dark:{
      color:'#FFFFFF',
    },
    text_light:{
      color:'#000000',
    },
    text_secondary:{
      color:'#FFFFFF',
    },
    input:{
      borderWidth:1,
      backgroundColor:'#FFF',marginHorizontal:'10%',
      fontSize:18,
      borderRadius:4,
      borderColor:'#cdcdcd',textAlign:'center'
    },
    em_linha_horizontal:{
      display:'flex',
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'center',
    },
    em_linha_vertical:{
      display:'flex',
      flexDirection:'column',
      alignItems:'center',
      justifyContent:'center',
    },
    flutuante:{
      position:'absolute',
    },
    top_right:{
      bottom:'auto',
      right:0,
      top:0,
      left:'auto',
    },
    top_Left:{
      bottom:'auto',
      right:'auto',
      top:0,
      left:0,
    },
    bottom_right:{
      bottom:0,
      right:0,
      top:'auto',
      left:'auto',
    },
    top_left:{
      bottom:0,
      right:'auto',
      top:'auto',
      left:0,
    },
    mr_5:{marginRight:5,},
    ml_5:{marginLeft:5,},
    mx_5:{marginHorizontal:5},
    fontMedium:{fontSize:20,marginVertical:2.5,marginTop:5}
});